### PR TITLE
[YUNIKORN-1351] alway prefer annotations above labels

### PR DESCRIPTION
**Pull request by chenyulin0719**
### What is this PR for?

1. Add description for new annotation 'disable-state-aware'.
2. Correct the priority descriptions. (Annotation > Label)
3. Fix typo.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
NA

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-1351

### Questions:
* [ ] - I added one more \<br\> to make the annotation/label priority description less crowded. Please let me know if it's not suggested.

### CODE REVIEW

**Comment by wilfred-s** [comment]
In the time that this PR has been open the text has been translated and the zh-cn file does not match anymore.
Also please make sure you do a format on the table. The table shows a warning that it is not properly formatted when loaded in an IDE. We try to keep the tables nicely aligned even in the base text format:
```
| ID | name                                            |
|----|-------------------------------------------------| 
| 1  | a value that also aligns in monospaced raw text |
```

**Comment by chenyulin0719** [comment]
Hi @wilfred-s,
I've manually formatted the table in 'en' document.
However, the  'zh-cn' word's width is not consistent with 'en', so I can't do the format here.

 image
 
Ex:
image

-> Unable to format  'zh-cn' table by adding space here.

**Comment by chenyulin0719** [comment]
Hi @wilfred-s,
May I know which IDE/Plugging you're using? I want to know how to check the warning of Markdown files?  
> The table shows a warning that it is not properly formatted when loaded in an IDE.

**Comment by wilfred-s** [comment]
I currently use Goland or Webstorm both are from [JetBrains](https://www.jetbrains.com)
They have a number of ways to get a free license

**Comment by chenyulin0719** [comment]
Pushed a new version after formated in Goland.

**Comment by chenyulin0719** [comment]
Close it as new policy for labels and annotations is defined in [YUNIKORN-1351](https://issues.apache.org/jira/browse/YUNIKORN-1351).

**Pull request closed without merging**
