### PR TITLE
[YUNIKORN-1380] Multiple pages URL were broken for website

### PR DESCRIPTION
**Pull request by jagadeesanas2**
Fix for trailingSlash issue.

### CODE REVIEW

**Review by craigcondit — APPROVED** [review]
+1, will merge shortly so we can test. It's possible we may need to revert if this makes things worse.

**Review by craigcondit — CHANGES_REQUESTED** [review]
Build failed on master. Please test this locally to be sure it builds.

**Review by craigcondit — CHANGES_REQUESTED** [review]
Syntax error during site generation.

**Comment by jagadeesanas2** [comment]
Fixed syntax error and created new PR with the local test build.

**Pull request closed without merging**
