### PR TITLE
[YUNIKORN-2614] Update website for 1.5.1

### PR DESCRIPTION
**Pull request by pbacsko**
### What is this PR for?
Update website for release 1.5.1

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [x] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2614

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by pbacsko** [comment]
ok, need to merge #429 first

**Review by craigcondit — COMMENTED** [review]
I wonder if we shouldn't skip the versioned_docs update and do the release announcement only. There are no documentation updates between 1.5.0 and 1.5.1, so we just introduce another version that needs to be built for every change moving forward.

**Comment by wilfred-s** [comment]
I think we need to do it the other way around: remove 1.5.0 and use 1.5.1 as the release. We do not want people to use 1.5.0 as the deadlocks are serious enough to make it a bad release.
Maybe also remove 1.5.0 from the downloads and replace with 1.5.1

**Review by wilfred-s — APPROVED** [review]
LGTM
We need to sort out what we do with patch releases and documentation and add it to the release procedure as part of the next release. Making ad-hoc decisions is not the right approach

**Pull request closed without merging**
