### PR TITLE
[YUNIKORN-2316] Update REST API docs for /ws/v1/scheduler/node-utilizations

### PR DESCRIPTION
**Pull request by chenyulin0719**
### What is this PR for?
1. Add /ws/v1/scheduler/node-utilizations endpoint doc.
2. Mark /ws/v1/scheduler/node-utilization deprecated.

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [x] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
NA

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2316

### Screenshots (if appropriate)
image

### Questions:
NA

### CODE REVIEW

**Comment by chia7712** [comment]
@chenyulin0719 could you please explain the reason of closing this PR?

**Comment by chenyulin0719** [comment]
@chia7712 Sorry, I forgot to update the Chinese files, soI closed it before anyone start to review it. I plan to open another PR after fixing it.

**Comment by chenyulin0719** [comment]
@chia7712  Sorry for causing you confusion. I should leave a comment and keep using the same PR.  
Reopen this PR.

**Comment by chenyulin0719** [comment]
@chia7712 Oh, I just realized that the PR can't be reopened after force-pushed.  Will create a new one.

**Pull request closed without merging**
