### PR TITLE
[YUNIKORN-2914] Update deployment documentation for extra description…

### PR DESCRIPTION
**Pull request by chenyao0910**
### What is this PR for?

I just saw there's a user asking about configmap hot reload question in the slack channel, can refer to[https://yunikornworkspace.slack.com/archives/CLNUW68MU/p1728327140557209]

I also checked the hot refresh part for Yunikorn's docs, and I think not everyone knows that if you mounted the configmap under the subpath, the hot reload will not be triggered.

Therefore, I want to add extra description about this part. 

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [x] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2914`

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by craigcondit — CHANGES_REQUESTED** [review]
The old information is accurate. The new information is not. We never mount the configmap at all. We use Kubernetes informers in the code to watch for changes automatically.

**Comment by chenyao0910** [comment]
I get it. thx for your explanation.

I'll close the PR.

**Comment by chenyao0910** [comment]
Another question, why we choose using informer rather than the hot reload by mount?

**Comment by craigcondit** [comment]
As the scheduler, we use informers to track changes to many other K8s objects already. Extending that to the configmap was easy. It also means we are more responsive to changes (mounted configmaps can take up to 30 seconds to be updated).

**Pull request closed without merging**
