### PR TITLE
[YUNIKORN-2936] Access K8s dashboard by port-forwarding

### PR DESCRIPTION
**Pull request by kousei47747**
### What is this PR for?
According to [this reported issue](https://github.com/kubernetes/dashboard/issues/8767), kubectl proxy strips the authorization header from the request, causing every login attempt to the K8s dashboard to result in a 401 Unauthorized error.
The recommended way to access the dashboard is by using port-forwarding.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2936

### CODE REVIEW

**Review by chenyulin0719 — COMMENTED** [review]
LGTM, @kousei47747  Could you also update 1.6.0 versioned page? It would be helpful for new beginners.

**Review by ryankert01 — APPROVED** [review]
lgtm, good simple change. (+1 on also update v1.6.0 before merge)

**Comment by kousei47747** [comment]
Thanks for reviewing!
1.6.0 versioned page has been updated, please check.

**Review by chenyulin0719 — APPROVED** [review]
LGTM

**Pull request closed without merging**
