### PR TITLE
[YUNIKORN-2111] Update core application state description in design document

### PR DESCRIPTION
**Pull request by chenyulin0719**
### What is this PR for?
1. Update to latest FSM chart (core application)
2. Correct Reject/Failed state description. (The application state could move to Expired.)

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
NA

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2111

### How should this be tested?
The FSM chart and statement for Failed/Rejected state should be updated.

### Screenshots (if appropriate)
scheduler_object_states(en)
scheduler_object_states(zh-cn)

### Questions:
NA

### CODE REVIEW

**Comment by chenyulin0719** [comment]
The 'New' state was represented by a red circle after creating the FSM graph. I can manually convert it to a black and white image if required.

**Comment by wilfred-s** [comment]
As per the comment in the jira: this should not be part of the design docs. It should be part of the developer guide itself, one level up, at best. The document shows states inside for objects inside the code. That is it shows what is currently implemented, not what was deigned a long time ago. That is something important for a developer, sometimes admin, and will change over time.

**Comment by chenyulin0719** [comment]
Hi @wilfred-s,

Just reviewed the document structure again.  
If I move the 'Scheduler Object States' to one level up, it will be mixed up with the 'How to' document.
(The argument point here is should we mixup it up?)

In my opionion, we can keep current implementation in the design document. 
As a new developer, checking the design document and understanding how things are currently implemented is quite straightforward for me. (If the design has been changed after 1.3.0, developer could check the old design by change the document version)

Or, we can discuss that should we create parent pages for below document types under developer guide?  
- 'How to' document 
- Current design and implementation
- Historical design and implementation

image

**Comment by wilfred-s** [comment]
I would place it after `Translation` document and before the `Design` folder.

**Comment by chenyulin0719** [comment]
Hi @wilfred-s, 
Just moved to the developer_guide, thanks for the advice.
Scheduler Object States Page (en)
Scheduler Object States Page (zh-cn)

**Review by wilfred-s — APPROVED** [review]
LGTM

**Pull request closed without merging**
