### PR TITLE
Add a missing newline in Tag Rule section

### PR DESCRIPTION
**Pull request by heumsi**
I think the newline is missing.

image

I add the newline.

### CODE REVIEW

**Comment by sunilgovind** [comment]
+ Wilfred for review

**Comment by sunilgovind** [comment]
@wilfred-s

**Comment by manirajv06** [comment]
@heumsi Can you create an account? You can use https://issues.apache.org/jira/secure/Signup!default.jspa. Once you create an account, will file a jira for this pr and assign it to you.

**Comment by heumsi** [comment]
I created my own account. username is heumsi

**Review by wilfred-s — APPROVED** [review]
LGTM

**Comment by wilfred-s** [comment]
I have created a jira for it. Please read the [how to contribute](https://yunikorn.apache.org/community/how_to_contribute/) page for the details on how we track issues etc.

**Pull request closed without merging**
