### PR TITLE
[YUNIKORN-2400] Upgrade docusaurus to 3.2

### PR DESCRIPTION
**Pull request by ryankert01**
### What is this PR for?

migrate docusaurus to v3.2 based on the [migration guide](https://docusaurus.io/docs/migration/v3).

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
N/A

### What is the Jira issue?

[YUNIKORN-2400](https://issues.apache.org/jira/browse/YUNIKORN-2400)

### How should this be tested?

```bash
./local-build.sh run
```

```bash
 docker build -t yunikorn/yunikorn-website:2.0.0 . --build-arg NODE_VERSION=18.19
```

### Screenshots (if appropriate)

Screenshot 2024-04-09 at 7 31 50 PM

### Questions:
N/A

### CODE REVIEW

**Comment by ryankert01** [comment]
Github Action omits an error indicating a problem that exists on the master branch(when you click on the `people` link in the footer section, 404 emerged), aka. resolve to the wrong url.

**Comment by ryankert01** [comment]
Actually, if you click a lot of times, it will become this:

```
https://yunikorn.apache.org/community/community/community/community/community/community/community/people
```

**Comment by ryankert01** [comment]
It's a tiny bug. I change `href` to `to` to solve it. Also, @steinsgateted can you help me re-run the github workflow? Thanks.

**Comment by ryankert01** [comment]
Hi, @wilfred-s , I hope this message finds you well. When you have a moment, could you please review my pr? I believe it addresses our mission to migrate docusaurus to v3.2. Your feedback would be greatly appreciated to move this forward.

Thank you for your time and assistance.

**Review by chenyulin0719 — APPROVED** [review]
LGTM, summary the compatible changes in this PR.
1. Escape '{', '}', '<' when it's just used as a character. ([Link](https://docusaurus.io/docs/migration/v3#common-mdx-problems))
2. Versioned Sidebars fixed. ([Link](https://docusaurus.io/docs/migration/v3#versioned-sidebars))

**Pull request closed without merging**
