### PR TITLE
[YUNIKORN-2909] Update the k8shim-application-state image

### PR DESCRIPTION
**Pull request by hiwangzhihui**
### What is this PR for?
The [YUNIKORN-1704](https://issues.apache.org/jira/browse/YUNIKORN-1704) issue in the 1.3 version has modified the shim-application_state

The [YUNIKORN-2180](https://issues.apache.org/jira/browse/YUNIKORN-2180) issue in the 1.5 version has modified the shim-application_state

The [YUNIKORN-2779](https://issues.apache.org/jira/browse/YUNIKORN-2779) issue in the 1.6 version has modified the shim-application_state

So， We need to update the （1.5、1.5.1、1.5.2、1.6 ）k8shim-application-state image

### What type of PR is it?
* Improvement

### What is the Jira issue?
* Open an issue on Jirahttps://issues.apache.org/jira/browse/YUNIKORN-2909

### CODE REVIEW

**Review by chenyulin0719 — COMMENTED** [review]
Hi @hiwangzhihui, thanks for bring this PR.

I know the chart is automatically generated by Graphviz, but the new image is not very readable. Is there any way to fine-tune the image?

image

**Comment by hiwangzhihui** [comment]
@ryankert01  Thanks for your review. I have completed the update.

**Comment by ryankert01** [comment]
cc @chenyulin0719 
Also, it seem you didn't update the next version?

**Review by chenyulin0719 — CHANGES_REQUESTED** [review]
Hi @hiwangzhihui, thanks for the update. 

I guess the reason you put color on the Running state's self-loop is to distinguish the clumsy strings. Am I right? 

If possible, could you share how to configure it so the following maintainers could do the same?

Please also update the next version image as @ryankert01 suggested, thanks.
(Under docs/assets/k8shim-application-state.png)

**Comment by hiwangzhihui** [comment]
@chenyulin0719  Yes, The  Yellow color is to distinguish the crowded strings.
This is 1.5.X_version  Graphviz code .
`digraph fsm {
    "Accepted" -> "Reserving" [ label = "AcceptApplication" ];
    "Accepted" -> "Failing" [ label = "CompleteApplication" ];
    "Accepted" -> "Killing" [ label = "FailApplication" ];
    "Accepted" -> "Running" [ label = "ReleaseAppAllocation" ];
    "Accepted" -> "Running" [ label = "UpdateReservation" ];
    "Failing" -> "Failed" [ label = "CompleteApplication" ];
   # "Failing" -> "Failing" [ label = "KilledApplication" ];
    "Failing" -> "Failing" [ label = "KilledApplication \n ReleaseAppAllocation" ];
    "Killing" -> "Killed" [ label = "KillApplication" ];
    "New" -> "Submitted" [ label = "SubmitApplication" ];
    "Rejected" -> "Failed" [ label = "CompleteApplication" ];
    "Reserving" -> "Resuming" [ label = "AppStateChange" ];
    "Reserving" -> "Failing" [ label = "CompleteApplication" ];
    "Reserving" -> "Killing" [ label = "FailApplication" ];
    "Reserving" -> "Running" [ label = "ReleaseAppAllocation" ];
    "Reserving" -> "Reserving" [ label = "TryReserve" ];
    "Reserving" -> "Running" [ label = "UpdateReservation" ];
    #"Resuming" -> "Resuming" [ label = "KilledApplication" ];
    #"Resuming" -> "Resuming" [ label = "ReleaseAppAllocation" ];
    "Resuming" -> "Resuming" [ label = "KilledApplication \n ReleaseAppAllocation \n ResumingApplication" ];
    "Resuming" -> "Running" [ label = "UpdateReservation" ];
    "Running" -> "Failing" [ label = "CompleteApplication" ];
    "Running" -> "Killing" [ label = "FailApplication" ];
    "Running" -> "Completed" [ label = "RejectApplication" ];
    #"Running" -> "Running" [ label = "KilledApplication" ];
    #"Running" -> "Running" [ label = "ReleaseAppAllocation" ];
    "Running" -> "Running"  [ label = "KilledApplication \n ReleaseAppAllocation \n UpdateReservation" fontcolor="#FFA500" color = "#FFA500"];
    "Submitted" -> "Failing" [ label = "CompleteApplication" ];
    "Submitted" -> "Accepted" [ label = "RecoverApplication" ];
    "Submitted" -> "Rejected" [ label = "RunApplication" ];

    "Accepted";
    "Completed";
    "Failed";
    "Failing";
    "Killed";
    "Killing";
    "New" ;
    "Rejected";
    "Reserving";
    "Resuming";
    "Running";
    "Submitted";
}
`

**Comment by chenyulin0719** [comment]
Hi @hiwangzhihui, could you help to update the image in the next version page?

image

**Comment by hiwangzhihui** [comment]
OK

**Comment by hiwangzhihui** [comment]
hi, @chenyulin0719   I have updated it.

**Pull request closed without merging**
