### PR TITLE
[YUNIKORN-2418] Improve clarity in Features docs

### PR DESCRIPTION
**Pull request by alex-stiff**
### What is this PR for?
This PR updates some wording in the features documentation to improve clarity and understanding.

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [x] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [x] - Add JIRA issue once ASF self service has created me an account

### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN/
* Put link here, and add [YUNIKORN-*Jira number*] in PR title, eg. `[YUNIKORN-2] Gang scheduling interface parameters`

### How should this be tested?

n/a

### Screenshots (if appropriate)

n/a

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by wilfred-s** [comment]
Please open a jra for tracking the changes, see https://yunikorn.apache.org/community/how_to_contribute for the process

**Comment by alex-stiff** [comment]
Thanks, updated.

**Comment by pbacsko** [comment]
@alex-stiff thanks for the PR, I've always believed we need something like that. 

Which part of the documentation have you read already?

**Comment by alex-stiff** [comment]
> @alex-stiff thanks for the PR, I've always believed we need something like that.
> 
> Which part of the documentation have you read already?

Mostly this page - as I go through the rest of it I'll be taking a look at the other docs pages as well.

**Review by craigcondit — APPROVED** [review]

**Pull request closed without merging**
